<a href="https://colab.research.google.com/github/Shahbaz-Junaid/Machine-Learning-Zero-to-Advanced/blob/main/Day_02_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 02 ML

In [2]:
# Why we fit and transform data

In [1]:
# Import necessary library
from sklearn.preprocessing import StandardScaler   # StandardScaler ko import kar rahe hain (data scaling ke liye)

import numpy as np   # Numpy import kar rahe hain arrays banane ke liye

# Create sample training data
X_train = np.array([[10], [20], [30], [40], [50]])
# Yeh hamara training data hai (5 values)

# Create sample test data
X_test = np.array([[60], [70]])
# Yeh test data hai jisko baad mein scale karenge

# Create object of StandardScaler
scaler = StandardScaler()
# Scaler ka object bana diya (abhi tak kuch learn nahi kiya)

# STEP 1: Fit the scaler on training data
scaler.fit(X_train)
# Yeh training data se mean aur standard deviation calculate karega
# Sirf seekhne ka kaam karta hai (data ko change nahi karta)

# STEP 2: Transform the training data
X_train_scaled = scaler.transform(X_train)
# Yeh training data ko scale karega using learned mean & std
# Formula use hota hai: (X - mean) / std

# STEP 3: Transform the test data
X_test_scaled = scaler.transform(X_test)
# Test data ko bhi same mean aur std se scale karega
# IMPORTANT: Test data par kabhi fit() nahi karte

# Print results
print("Original Training Data:\n", X_train)
# Original training data print karega

print("\nScaled Training Data:\n", X_train_scaled)
# Scaled training data print karega

print("\nOriginal Test Data:\n", X_test)
# Original test data print karega

print("\nScaled Test Data:\n", X_test_scaled)
# Scaled test data print karega


Original Training Data:
 [[10]
 [20]
 [30]
 [40]
 [50]]

Scaled Training Data:
 [[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

Original Test Data:
 [[60]
 [70]]

Scaled Test Data:
 [[2.12132034]
 [2.82842712]]


In [3]:
# 🔹 fit() kya karta hai?
# ✅ Roman Urdu:

# fit() data ko dekh kar seekhta hai.
# Jaise mean (average) aur standard deviation calculate karta hai.

# Matlab:

# Data se rules learn karna.

# ✅ English:

# fit() learns parameters from the data.
# For example, it calculates mean and standard deviation.

# 🔹 transform() kya karta hai?
# ✅ Roman Urdu:

# transform() woh rules jo fit() ne seekhe thay, unko data par apply karta hai.
# Yani data ko scale ya convert karta hai.

# Matlab:

# Learned rules apply karna.

# ✅ English:

# transform() applies the learned parameters to modify the data.

# Cross Validation in ML

In [6]:
# ✅ Roman Urdu:

# Cross Validation ek
#  technique hai jisme hum model ko multiple baar train aur test karte hain taake model ka performance zyada accurate measure ho.

# Yani:

# Sirf ek baar train/test split karne ke bajaye, data ko multiple parts mein divide karte hain.

# ✅ English:

# Cross Validation is a technique where we train and test the model multiple times on different splits of
# data to get a more reliable performance score.

In [7]:
# Step 1: Libraries import
from sklearn.model_selection import cross_val_score  # Cross validation ke liye
from sklearn.linear_model import LinearRegression    # Model
from sklearn.datasets import make_regression        # Dummy dataset banane ke liye

# Step 2: Dummy dataset create karte hain
X, y = make_regression(n_samples=100, n_features=3, noise=10)
# 100 samples ka dataset create ho gaya

# Step 3: Model create karte hain
model = LinearRegression()

# Step 4: Cross Validation apply karte hain (K=5)
scores = cross_val_score(model, X, y, cv=5)
# cv=5 matlab 5-fold cross validation

# Step 5: Scores print karte hain
print("Cross Validation Scores:", scores)
# Har fold ka score print karega

print("Average Score:", scores.mean())
# Average performance batayega


Cross Validation Scores: [0.99319285 0.98783979 0.98082576 0.9870648  0.99289562]
Average Score: 0.9883637646339049


In [12]:
# Yeh overfitting kam karta hai

# Model ki real performance batata hai

# # Zyada reliable result deta hai

# simple way to train_test_split

In [13]:
# Step 1: Libraries import
from sklearn.datasets import load_iris      # Iris dataset
from sklearn.model_selection import train_test_split  # Data split karne ke liye
from sklearn.linear_model import LogisticRegression   # Model
from sklearn.metrics import accuracy_score  # Accuracy check karne ke liye

# Step 2: Dataset load karo
iris = load_iris()
X = iris.data      # Features
y = iris.target    # Target labels

# Step 3: Train/Test split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Model create karo
model = LogisticRegression(max_iter=200)

# Step 5: Model train karo
model.fit(X_train, y_train)

# Step 6: Prediction karo
y_pred = model.predict(X_test)

# Step 7: Accuracy check karo
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy without Cross Validation:", accuracy)


Accuracy without Cross Validation: 1.0


# Using Cross Validation

In [17]:
# Step 1: Libraries import
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

# Step 2: Dataset load karo
iris = load_iris()
X = iris.data
y = iris.target

# Step 3: Model create karo
model = LogisticRegression(max_iter=200)

# Step 4: Apply 5-Fold Cross Validation
scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

# Step 5: Results print karo
print("Accuracy in each fold:", scores)
print("Average Accuracy:", scores.mean())


Accuracy in each fold: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Accuracy: 0.9733333333333334


In [18]:
# Step 1: Libraries import
from sklearn.datasets import load_diabetes   # Regression dataset
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

# Step 2: Dataset load
data = load_diabetes()
X = data.data
y = data.target

# Step 3: Model create
model = LinearRegression()

# Step 4: Cross Validation apply (5-fold)
scores = cross_val_score(model, X, y, cv=5, scoring='r2')

# Step 5: Results
print("R2 Scores:", scores)
print("Average R2 Score:", scores.mean())


R2 Scores: [0.42955615 0.52259939 0.48268054 0.42649776 0.55024834]
Average R2 Score: 0.48231643590864215
