<a href="https://colab.research.google.com/github/Shahbaz-Junaid/Machine-Learning-Zero-to-Advanced/blob/main/Day_01_Group_Study_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning Day 01 code Series

# Standardization

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame({
    "Height": [170, 180, 160],
    "Weight": [70, 80, 60]
})

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


# is ma hum agr high value aya tu us ko kam karta hai aur is ko 0 ya 1 k b/w lata hai


[[ 0.          0.        ]
 [ 1.22474487  1.22474487]
 [-1.22474487 -1.22474487]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
# Set random seed for reproducibility
np.random.seed(42)

# Create 100 rows with 10 feature columns
X = pd.DataFrame(
    np.random.rand(100, 10),
    columns=[f'feature_{i}' for i in range(1, 11)]
)

# Create a binary target column
y = np.random.randint(0, 2, 100)

# Combine into one DataFrame (optional)
df = X.copy()
df['target'] = y

print(df.head())


   feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0   0.374540   0.950714   0.731994   0.598658   0.156019   0.155995   
1   0.020584   0.969910   0.832443   0.212339   0.181825   0.183405   
2   0.611853   0.139494   0.292145   0.366362   0.456070   0.785176   
3   0.607545   0.170524   0.065052   0.948886   0.965632   0.808397   
4   0.122038   0.495177   0.034389   0.909320   0.258780   0.662522   

   feature_7  feature_8  feature_9  feature_10  target  
0   0.058084   0.866176   0.601115    0.708073       0  
1   0.304242   0.524756   0.431945    0.291229       1  
2   0.199674   0.514234   0.592415    0.046450       1  
3   0.304614   0.097672   0.684233    0.440152       1  
4   0.311711   0.520068   0.546710    0.184854       1  


In [ ]:
X_train, X_test, y_train, y_test,= train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# means = X_train.mean()
# stds = X_train.std()
# X_train_scaled_0 = (X_train[:1] - means) / stds
# print(X_train_scaled_0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled.shape

(80, 10)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
# scaled the test for making model prediction
X_test_scaled = scaler.transform(X_test)
y_pred = model.predict(X_test_scaled)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.4


In [ ]:
confusion_matrix(y_test, y_pred)

array([[ 7,  2],
       [10,  1]])

In [ ]:
df = pd.DataFrame([[12, 34,54,65,12,45,76,33,54,3]], columns=[f'feature_{i}' for i in range(1, 11)])
df

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10
0,12,34,54,65,12,45,76,33,54,3


In [ ]:
df_scaled = scaler.transform(df)

In [ ]:
df_scaled

array([[ 38.6014782 , 118.53911985, 186.07779591, 248.91810872,
         38.69040938, 154.32742133, 282.88558185, 111.73870603,
        165.95772163,   8.60258183]])

In [ ]:
model.predict(df_scaled)

array([0])

# Making the Machine Learning Pipeline

In [ ]:
from sklearn.pipeline import Pipeline

pipeline_lg = Pipeline([
    ('scaler', StandardScaler()),
    ('lg', LogisticRegression(random_state=42))
])

pipeline_lg.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lg', LogisticRegression(random_state=42))])

In [ ]:
y_pred = pipeline_lg.predict(X_test)

In [ ]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.4


In [ ]:
pipeline_lg.predict(df)

array([0])

In [ ]:
# Normaization
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([[10], [20], [30], [40], [50]])

scaler = MinMaxScaler()  #this is the type or technique of # Normaization
normalized_data = scaler.fit_transform(data)

print(normalized_data)


[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
